WebApplication/Models/ReactivesRemainings/RemainingsDetailsModel.cs
using System.Collections.Generic;

namespace WebApplication.Models.ReactivesRemainings
{
    /// <summary> Модель данных для детализации по остаткам </summary>
    public class RemainingsDetailsModel
    {
        /// <summary> Номер специяфикации </summary>
        public int SpecificationId { get; set; }

        /// <summary> Название спецификации </summary>
        public string SpecificationName { get; set; }

        /// <summary> Структура данных, описывающая поставку</summary>
        public struct ArrivalInfo
        {
            /// <summary> Номер серии ЛКК</summary>
            public string Lkksn { get; set; }

            /// <summary> Количество статков в серии</summary>
            public decimal? Count { get; set; }

            /// <summary> Единицы измерения в серии</summary>
            public string MesUnits { get; set; }

            /// <summary> Место хранения поставки </summary>
            public string StoredAt { get; set; }

            /// <summary> Статус списания</summary>
            public bool IsWrittenOff { get; set; }
        }

        /// <summary> Перечисление поставок по указанной спецификации</summary>
        public IEnumerable<ArrivalInfo> Arrivals { get; set; }
    }
}

WebApplication/Models/ReactivesRemainings/RemainingsIndexFilterModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplication.Models.ReactivesRemainings
{
    /// <summary> Модель данных для поиска и представления результатов по остаткам </summary>
    public class RemainingsIndexFilterModel
    {
        /// <summary> Строки обнаруженных остатков для вывода в качестве результатов поиска </summary>
        public IEnumerable<RemainingsIndexResultRowModel> Rows { get; set; }

        /// <summary> Перечисление атрибутов в базе данных: код-название </summary>
        public Dictionary<char, string> Attributes { get; set; }

        /// <summary> выбранные атрибуты для одбавление по правилу "только с атрибутом" </summary>
        public Dictionary<char, bool> SelectedAttributesOn { get; set; }

        /// <summary> Выбранные атрибуты для добавления по правилу "только без атрибута" </summary>
        public Dictionary<char, bool> SelectedAttributesOff { get; set; }

        /// <summary> Спецификации базы данных </summary>
        public IEnumerable<SelectListItem> Specifications { get; set; }

        /// <summary> Фильтр по выбранной спейификации </summary>
        public int? SelectedSpecificationFilter { get; set; }

        /// <summary> Фильтр по введённому значению в имени спецификации </summary>
        public string InsertedSpecificationFilter { get; set; }

        /// <summary> Пункты выбора "списан ли" </summary>
        public IEnumerable<SelectListItem> IsWrittenOffFilterItems => new List<SelectListItem>
        {
            new SelectListItem("не списанные", "no", true),
            new SelectListItem("списанные", "yes", false),
            new SelectListItem("все", "any", false)
        };

        /// <summary> Выбранный пункт из вариантов "списан ли" </summary>
        public string IsWrittenOffSelectedFilter { get; set; } = "no";

        /// <summary> Ограничение по количеству выводимых данных</summary>
        public int Limit { get; set; } = 25;
    }
}

WebApplication/Models/ReactivesRemainings/RemainingsIndexResultRowModel.cs
using System;
using System.Collections.Generic;

namespace WebApplication.Models.ReactivesRemainings
{
    public class RemainingsIndexResultRowModel : IEquatable<RemainingsIndexResultRowModel>
    {
        /// <summary> Номер спецификации </summary>
        public int? SpecificationNumber { get; set; }

        /// <summary> Название спецификации </summary>
        public string SpecificationName { get; set; }

        /// <summary> Структура "Остаток" </summary>
        public struct RemainingCount
        {
            /// <summary> Числовое значение остатка </summary>
            public decimal? Value { get; set; }

            /// <summary> Единица измерения </summary>
            public string MesUnit { get; set; }
        }

        /// <summary> Остатки указанной спецификации по единицам измерения </summary>
        public IEnumerable<RemainingCount> Counts { get; set; }

        public bool Equals(RemainingsIndexResultRowModel other)
            => SpecificationNumber == other?.SpecificationNumber;

        public override bool Equals(object obj)
            => obj is RemainingsIndexResultRowModel other && Equals(other);

        public override int GetHashCode() 
            => HashCode.Combine(SpecificationNumber);
    }
}

WebApplication/Controllers/ReactivesRemainingsController.cs
using System.Data;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication.Models.ReactivesRemainings;
using WebApplication.Tools.DbConnector;
using WebApplication.Tools.Project;

namespace WebApplication.Controllers
{
    /// <summary> Отчёты по остаткам реактивов </summary>
    [Authorize]
    public class ReactivesRemainingsController : Controller
    {
        /// <summary>Сервис связи с базой данных</summary>
        private readonly IDbConnector _connector;

        /// <summary> Конструктор запрашивает необхоидмые сервисы</summary>
        /// <param name="connector">Связь с базой данных</param>
        public ReactivesRemainingsController(IDbConnector connector)
            => _connector = connector;
        
        /// <summary> Просмотр и фильтрация остатков </summary>
        /// <param name="model">Модель фильтрации и представления данных </param>
        public IActionResult Index(RemainingsIndexFilterModel model)
        {
            model ??= new RemainingsIndexFilterModel();
            if (model.Limit < 1 || model.Limit > 999) model.Limit = 25;

            if (model.Attributes == null || !model.Attributes.Any())
            {
                if (!_connector.TryReadData("select \"code\", \"name\" from \"Reactives_Attributes\";",
                    out var atrData, out var error))
                    return this.Error("Ошибка базы данных", "При загрузке данных произошла ошибка. " + error);

                model.Attributes = atrData == null || atrData.Rows.Count < 1
                    ? null
                    : atrData.Rows.Cast<DataRow>()
                        .ToDictionary(x => x.GetValue("code")[0], y => y.GetValue("name"));
            }

            if (model.SelectedAttributesOn == null || !model.SelectedAttributesOn.Any())
                model.SelectedAttributesOn = model.Attributes?.ToDictionary(x => x.Key, y => false);

            if (model.SelectedAttributesOff == null || !model.SelectedAttributesOff.Any())
                model.SelectedAttributesOff = model.Attributes?.ToDictionary(x => x.Key, y => false);

            if (model.Specifications == null || !model.Specifications.Any())
            {
                if (!_connector.TryReadData("select \"Id\", \"name\" from \"Reactives_Specifications\";",
                    out var specData, out var error)) 
                    return this.Error("Ошибка базы данных", "При загрузке данных произошла ошибка. " + error);

                model.Specifications = specData == null || specData.Rows.Count < 1
                    ? null
                    : specData.Rows.Cast<DataRow>()
                        .Select(x => new SelectListItem(x.GetValue("name"), x.GetValue("Id"), false));
            }

            var builder = new StringBuilder
            (
                "select " +
                    "s.\"Id\" as \"spec_id\", " +
                    "s.\"name\" as \"spec_name\", " +
                    "sum(a.\"current_state_count\") as \"count_remain\", " +
                    "a.\"start_state_mes_unit_name\" as \"mes_unit\" " +
                "from \"Reactives_Arrivals\" a " +
                    "inner join \"Reactives_Specifications\" s on a.\"LKKSN_specification_id\" = s.\"Id\" " +
                "where a.\"current_state_count\" <> 0 "
            );

            if (model.SelectedAttributesOn != null)
                foreach (var on in model.SelectedAttributesOn.Where(x => x.Value))
                    builder.Append($" and a.\"current_state_attribute_string\" like \'%{on.Key}%\' ");

            if (model.SelectedAttributesOff != null)
                foreach (var off in model.SelectedAttributesOff.Where(x => x.Value))
                    builder.Append(" and (a.\"current_state_attribute_string\" is null " +
                                   $"or a.\"current_state_attribute_string\" not like \'%{off.Key}%\') ");

            if (!string.IsNullOrWhiteSpace(model.InsertedSpecificationFilter))
                builder.Append($" and s.\"upper_name\" like \'%{model.InsertedSpecificationFilter.ToUpper()}%\' ");
            else if (model.SelectedSpecificationFilter != null)
                builder.Append($"and a.\"LKKSN_specification_id\" = {model.SelectedSpecificationFilter}");

            switch (model.IsWrittenOffSelectedFilter)
            {
                case "no":
                    builder.Append(" and a.\"current_state_is_written_off\" = 0 ");
                    break;
                case "yes":
                    builder.Append(" and a.\"current_state_is_written_off\" = 1 ");
                    break;
            }

            builder.Append(" group by a.\"LKKSN_specification_id\", \"start_state_mes_unit_name\" " +
                           $" order by s.\"Id\" limit {model.Limit}; ");

            if (!_connector.TryReadData(builder.ToString(), out var data, out var gError))
                return this.Error("Ошибка базы данных", "При загрузке данных по выбранным фильтрам произошла ошибка. " + gError);

            if (data == null || data.Rows.Count < 1)
                return View(model);

            model.Rows = data.Rows.Cast<DataRow>()
                .Select(x => new RemainingsIndexResultRowModel
                {
                    SpecificationNumber = x.GetInt("spec_id"),
                    SpecificationName = x.GetValue("spec_name"),
                    Counts = data.Rows.Cast<DataRow>()
                        .Where(y => y.GetInt("spec_id") == x.GetInt("spec_id"))
                        .Select(y => new RemainingsIndexResultRowModel.RemainingCount
                        {
                            Value = y.GetDecimal("count_remain"),
                            MesUnit = y.GetValue("mes_unit")
                        })
                }).Distinct();

            return View(model);
        }

        /// <summary> Детали по остаткам выбранной спецификации </summary>
        /// <param name="id">Номер спецификации</param>
        public IActionResult Details(int? id)
        {
            if (id == null)
                return this.Error("Системная ошибка", 
                    "Остатки, детали. Запрос не содержит номера спецификации. Обратитесь к разработчику.");

            var specName = _connector.GetValue($"select \"name\" from \"Reactives_Specifications\" where \"Id\" = {id}", out var error);
            if (string.IsNullOrWhiteSpace(specName))
                return this.Error("Ошибка базы данных",
                    "Остатки, детали. Пои поиске спецификации в базе данных произошла ошибка. " + error);

            if (!_connector.TryReadData
            (
                "select " +
                    "\"LKKSN\" as \"lkksn\", " +
                    "\"current_state_count\" as \"count\", " +
                    "\"start_state_mes_unit_name\" as \"mes_units\", " +
                    "\"current_state_stored_at\" as \"stored_at\", " +
                    "\"current_state_is_written_off\" as \"is_written_off\" " +
                "from \"Reactives_Arrivals\" " +
                $"where \"LKKSN_specification_id\" = {id} and \"current_state_count\" <> 0",
                out var data,
                out error
            ))
                return this.Error("Ошибка базы данных",
                    "Остатки, детали. При поиске информации в базе данных произошла ошибка. " + error);

            var model = new RemainingsDetailsModel
            {
                SpecificationId = (int) id,
                SpecificationName = specName
            };

            if (data == null || data.Rows.Count < 1)
                return View(model);

            model.Arrivals = data.Rows.Cast<DataRow>()
                .Select(x => new RemainingsDetailsModel.ArrivalInfo
                {
                    Lkksn = x.GetValue("lkksn"),
                    Count = x.GetDecimal("count"),
                    MesUnits = x.GetValue("mes_units"),
                    StoredAt = x.GetValue("stored_at"),
                    IsWrittenOff = x.GetValue("is_written_off") == "1"
                });

            return View(model);
        }

    }
}

WebApplication/Views/ReactivesRemainings/Details.cshtml
@model WebApplication.Models.ReactivesRemainings.RemainingsDetailsModel
@{
    ViewData["Title"] = "Детализация остатков по спецификации";
    var notWrittenOff = Model?.Arrivals?.Where(x => !x.IsWrittenOff).ToArray();
    var writtenOff = Model?.Arrivals?.Where(x => x.IsWrittenOff).ToArray();
}

<h2>@ViewData["Title"]</h2>


<div>
    <b>Спецификация</b>
    @Model?.SpecificationId - @Model?.SpecificationName
</div>
<hr />
<h4>Не списанные</h4>
<div>
    @if (notWrittenOff == null || !notWrittenOff.Any())
    {
        <span style="color: gray; font-size: small">Не списанные поставки c ненулевыми остатками не обнаружены</span>
    }
    else
    {
        <table class="table-bordered hightlightrows">
            <tr>
                <th style="text-align: center">Серия ЛКК</th>
                <th style="text-align: center">Остаток</th>
                <th style="text-align: center">Место хранения</th>
            </tr>

            @foreach (var item in notWrittenOff)
            {
                <tr>
                    <td>
                        <a asp-controller="Reactives" asp-action="Info" asp-route-lkksn="@item.Lkksn">
                            @item.Lkksn
                        </a>
                    </td>
                    <td>@item.Count @item.MesUnits</td>
                    <td>@item.StoredAt</td>
                </tr>
            }
        </table>
    }
</div>
<hr />
<h4>Списанные</h4>
<div>
    @if (writtenOff == null || !writtenOff.Any())
    {
        <span style="color: gray; font-size: small">Не списанные поставки c ненулевыми остатками не обнаружены</span>
    }
    else
    {
        <table class="table-bordered hightlightrows">
            <tr>
                <th style="text-align: center">Серия ЛКК</th>
                <th style="text-align: center">Остаток</th>
                <th style="text-align: center">Место хранения</th>
            </tr>

            @foreach (var item in writtenOff)
            {
                <tr>
                    <td>
                        <a asp-controller="Reactives" asp-action="Info" asp-route-lkksn="@item.Lkksn">
                            @item.Lkksn
                        </a>
                    </td>
                    <td>@item.Count @item.MesUnits</td>
                    <td>@item.StoredAt</td>
                </tr>
            }
        </table>
    }
</div>

WebApplication/Views/ReactivesRemainings/Index.cshtml
@model WebApplication.Models.ReactivesRemainings.RemainingsIndexFilterModel
@{
    ViewData["Title"] = "Остатки реактивов";
}

<h2>@ViewData["Title"]</h2>

<h4>
    <input type="checkbox" id="filter_chb" onclick="ShowHide('filter_chb', 'filter_div')" />
    <label for="filter_chb">Поиск</label>
</h4>

<div id="filter_div" style="display: none">
    <form asp-controller="ReactivesRemainings" asp-action="Index">
        <table>
            <tr>
                <th>Спецификации</th>
                <td>
                    <input type="text" asp-for="InsertedSpecificationFilter" />
                    <select asp-for="SelectedSpecificationFilter" asp-items="@Model.Specifications">
                        <option value=""></option>
                    </select>
                </td>
            </tr>
            <tr>
                <th>Статус списания</th>
                <td>
                    @foreach (var state in Model.IsWrittenOffFilterItems)
                    {
                        <input type="radio" asp-for="IsWrittenOffSelectedFilter" value="@state.Value" id="fwo_@state.Value" checked="@state.Selected" />
                        <label for="fwo_@state.Value">@state.Text</label>
                    }
                </td>
            </tr>
            <tr>
                <th style="vertical-align: top">С указанными атрибутами</th>
                <td>
                    @if (Model.Attributes != null && Model.Attributes.Any())
                    {
                        @foreach (var pair in Model.SelectedAttributesOn)
                        {
                            @Html.CheckBoxFor(m => m.SelectedAttributesOn[pair.Key], pair.Value)
                            <label for="SelectedAttributesOn_@(pair.Key)_">
                                @if (Model.Attributes.ContainsKey(pair.Key))
                                {
                                    <text>@Model.Attributes[pair.Key]</text>
                                }
                                else
                                {
                                    <text>Атрибут @pair.Value</text>
                                }
                            </label>
                        }
                    }
                    else
                    {
                        <span>Атрибуты в базе данных не зарегистрированы</span>
                    }
                </td>
            </tr>
            <tr>
                <th style="vertical-align: top">Без указанных атрибутов</th>
                <td>
                    @if (Model.Attributes != null && Model.Attributes.Any())
                    {
                        @foreach (var pair in Model.SelectedAttributesOff)
                        {
                            @Html.CheckBoxFor(m => m.SelectedAttributesOff[pair.Key], pair.Value)
                            <label for="SelectedAttributesOff_@(pair.Key)_">
                                @if (Model.Attributes.ContainsKey(pair.Key))
                                {
                                    <text>@Model.Attributes[pair.Key]</text>
                                }
                                else
                                {
                                    <text>Атрибут @pair.Value</text>
                                }
                            </label>
                        }
                    }
                    else
                    {
                        <span>Атрибуты в базе данных не зарегистрированы</span>
                    }
                </td>
            </tr>
            <tr>
                <th>Показать</th>
                <td>
                    <input type="text" asp-for="Limit" style="width: 35px" maxlength="3"/> строк
                </td>
            </tr>
        </table>
        <div style="text-align: center">
            <a asp-controller="ReactivesRemainings" asp-action="Index" style="text-decoration: none">
                <input type="button" class="btn btn-outline-dark margined-for-5px" value="Сброс"/>
            </a>
            <input type="submit" class="btn btn-outline-dark margined-for-5px" value="Поиск"/>
        </div>
    </form>
</div>

<h4>Результаты поиска</h4>

<div style="color: gray; font-size: small; margin: 0 0 7px 0">
    Ограничение вывода - не более @Model.Limit (строк)
</div>

@if (Model.Rows == null || !Model.Rows.Any())
{
    <div>
        Остатки реактивов по выбранным фильтрам не обнаружены.
    </div>
}
else
{
<table class="table-bordered hightlightrows">
    <tr>
        <th style="text-align: center;">Спецификация</th>
        <th style="text-align: center;max-width: 200px"> Остатки</th>
        <th style="text-align: center;width: 100px">Инструмент</th>
    </tr>
    @foreach (var row in Model.Rows)
    {
        <tr>
            <td style="vertical-align: top">
                <a asp-controller="ReactivesRemainings" asp-action="Details" asp-route-id="@row.SpecificationNumber" target="_blank">
                    @row.SpecificationNumber - @row.SpecificationName
                </a>
            </td>
            <td>
                @if (row.Counts == null || !row.Counts.Any())
                {
                    <span style="color: gray; font-size: small">-не обнаружено-</span>
                }
                else
                {
                    var first = true;
                    @foreach (var count in row.Counts)
                    {
                        if (first)
                        {
                            first = false;
                        }
                        else
                        {
                            <br/>
                        } 
                        <text>- @count.Value @count.MesUnit</text>
                    }
                }
            </td>
            <td style="text-align: center; vertical-align: top">
                <a asp-controller="ReactivesRemainings" asp-action="Details" asp-route-id="@row.SpecificationNumber" target="_blank"
                   style="text-decoration: none" title="Подробности по остаткам в этой спецификации">
                    <img src="~/images/icon-info.png" class="img-mini-btn-icon margined-for-5px" alt="[?]" />
                </a>
            </td>
        </tr>
    }
</table>
}