WebApplication/Models/ReactivesMoving/MovingIndexResultsRowModel.cs
using System;

namespace WebApplication.Models.ReactivesMoving
{
    /// <summary> Структура данных для строк в результатах поиска прихода и расхода реактивов </summary>
    public class MovingIndexResultsRowModel
    {
        /// <summary> Дата и время изменения</summary>
        public DateTime? MovingDateTime { get; set; }

        /// <summary> Номер спецификации </summary>
        public int? SpecificationId { get; set; }

        /// <summary> Название спецификации </summary>
        public string SpecificationName { get; set; }

        /// <summary>Серия ЛКК поставки реактива</summary>
        public string Lkksn { get; set; }
        
        /// <summary>На какую величину изменилась поставка</summary>
        public decimal Difference { get; set; }

        /// <summary>Единица измерения, на которую поменялись данные</summary>
        public string MesUnits { get; set; }

        /// <summary> Комментарий к изменению данных</summary>
        public string RecordComment { get; set; }

        /// <summary> Пользователь, изменивший данные</summary>
        public string UserName { get; set; }
    }
}

WebApplication/Controllers/ReactivesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication.Tools.DbConnector;
using WebApplication.Tools.Project;
using WebApplication.Models.Reactives;

namespace WebApplication.Controllers
{
    /// <summary> Управление поставками реактивов и расходных материалов </summary>
    [Authorize]
    public class ReactivesController : Controller
    {
        /// <summary> Сервис связи с базой данных </summary>
        private readonly IDbConnector _connector;

        /// <summary> Конструктор собирает нужные сервисы</summary>
        /// <param name="connector">Сервис базы данных</param>
        public ReactivesController(IDbConnector connector)
            => _connector = connector;

        /// <summary> Просмотр и фильтрация поставок </summary>
        /// <param name="model">Модель представления: фильтры и результаты</param>
        public IActionResult Index(ReactivesIndexFilterModel model)
        {
            #region Поиск различных перечислений для списков

            // (будет использован позже) снимает с модели поднятые флаги по атрибутам (сотрёт их следующим шагом)
            var filterAttributes = model.Filter_Attributes
                ?.Where(x => x.Value)
                .Select(x => x.Key)
                .ToArray();

            try
            {
                model.Specifications = GetSpecifications();
                model.Producers = GetProducers();
                model.Providers = GetProviders();
                var attributes = GetAttributes();
                model.Filter_Attributes = attributes?.ToDictionary(x => x.Key, y => false);
                model.AttributesNames = attributes;
            }
            catch (Exception e)
            {
                return this.Error("Ошибка базы данных", e.Message);
            }

            #endregion

            #region Поиск реактивов по имеющимся данным

            var request = new StringBuilder
            (
                "select " +
                    "a.\"LKKSN\", " +
                    "s.\"name\" as \"specification\", " +
                    "a.\"current_state_count\" as \"count\", " +
                    "a.\"current_state_is_written_off\" as \"is_written_off\", " +
                    "u.\"short\" as \"unit\", " +
                    "a.\"current_state_valid_forever\" as \"valid_forever\", " +
                    "a.\"current_state_valid_until_date\" as \"valid_until\" " +
                "from \"Reactives_Arrivals\" a " +
                    "inner join \"Reactives_Specifications\" s on a.\"LKKSN_specification_id\" = s.\"Id\" " +
                    "inner join \"Reactives_Mes_Units\" as u on u.\"name\" = a.\"start_state_mes_unit_name\" "
            );

            var isFirst = true;
            string AndWhere()
            {
                if (!isFirst) return " and ";
                isFirst = false;
                return " where ";
            }

            // по выбранному периоду по году и месяцу (независимо)
            if (model.Filter_YearInserted != null)
            {
                var year = (int) model.Filter_YearInserted;
                if (year <= 0) year = DateTime.Today.AddYears(year).Year;
                else if (year <= 99) year += 2000;

                if (year < 1900 || year > DateTime.Today.Year)
                {
                    ModelState.AddModelError("", "В поле фильтра по году введено неприемлемое значение");
                    return View(model);
                }

                if (model.Filter_MonthSelected < 1)
                    request.Append(AndWhere() + $" \"LKKSN_date\" like \'{year}-%\' ");
                else
                    request.Append(AndWhere() + $" \"LKKSN_date\" like \'{year}-{model.Filter_MonthSelected:D2}-%\' ");
            }
            else if (model.Filter_MonthSelected > 0)
            {
                request.Append(AndWhere() + $" \"LKKSN_date\" like \'____-{model.Filter_MonthSelected:D2}-%\' ");
            }

            // по выбранной спецификации и части её имени
            if (model.Filter_Lkksn_SpecificationSelected > 0)
                request.Append(AndWhere() + $" \"LKKSN_specification_id\" = {model.Filter_Lkksn_SpecificationSelected} ");
            if (!string.IsNullOrWhiteSpace(model.Filter_SpecificationNameLike))
                request.Append(AndWhere() + $" s.\"upper_name\" like  \'%{model.Filter_SpecificationNameLike.ToUpper()}%\' ");

            // по введённым элементам серии ЛКК
            if (!string.IsNullOrWhiteSpace(model.Filter_Lkksn_SpecificationLike))
                request.Append(AndWhere() + $" \"LKKSN\" like \'%{model.Filter_Lkksn_SpecificationLike}/%/%\' ");
            if (!string.IsNullOrWhiteSpace(model.Filter_Lkksn_NumberLike))
                request.Append(AndWhere() + $" \"LKKSN\" like \'%/%{model.Filter_Lkksn_NumberLike}/%\' ");
            if (model.Filter_Lkksn_Date != null)
                request.Append(AndWhere() + $" \"LKKSN\" like \'%/%/{model.Filter_Lkksn_Date?.ToString("ddMMyy")}\' ");

            // по типу статуса списания
            switch (model.Filter_WrittenOff)
            {
                case "no":
                    request.Append(AndWhere() + " \"current_state_is_written_off\" = \'0\' ");
                    break;
                case "yes":
                    request.Append(AndWhere() + " \"current_state_is_written_off\" = \'1\' ");
                    break;
            }

            // по производителю и поставщику
            if (model.Filter_ProducerSelected > 0)
                request.Append(AndWhere() + $" \"producer_id\" = {model.Filter_ProducerSelected} ");
            if (model.Filter_ProviderSelected > 0)
                request.Append(AndWhere() + $" \"provider_id\" = {model.Filter_ProviderSelected} ");

            // по атрибутам
            if (filterAttributes != null && filterAttributes.Any())
                foreach (var c in filterAttributes)
                    request.Append(AndWhere() + $" \"current_state_attribute_string\" like \'%{c}%\' ");

            // по содержанию комментария
            if (!string.IsNullOrWhiteSpace(model.Filter_CommentsLike))
                request.Append(AndWhere() + $" \"current_state_comments\" like \'%{model.Filter_CommentsLike}%\' ");

            // сортировка и ограничение выборки
            switch (model?.SortBySelected)
            {
                case "date_old":
                    request.Append(" order by a.\"LKKSN_date\" asc ");
                    break;
                case "lkksn":
                    request.Append(" order by a.\"LKKSN\" asc ");
                    break;
                case "created_at_old": 
                    request.Append(" order by a.\"created_at_date\" asc ");
                    break;
                case "created_at_new": 
                    request.Append(" order by a.\"created_at_date\" desc ");
                    break;
                case "changed_at_old":
                    request.Append(" order by a.\"changed_at_date\" asc ");
                    break;
                case "changed_at_new":
                    request.Append(" order by a.\"changed_at_date\" desc ");
                    break;
                default:
                    request.Append(" order by a.\"LKKSN_date\" desc ");
                    break;
            }

            if (model.ResultRowsCountLimit <= 0)
                model.ResultRowsCountLimit = 25;
            request.Append(" limit " + model.ResultRowsCountLimit);

            if (!ModelState.IsValid) return View(model);

            if (!_connector.TryReadData(request.ToString(), out var data, out var error))
                return this.Error("Ошибка базы данных",
                    "При попытке загрузить данные о поставках реактивов произошла ошибка. " + error +
                    "Обратитесь к разработчику");

            model.Reactives = data?.Rows.Cast<DataRow>()
                .Select(x => new ReactivesIndexModel
                {
                    Lkksn = x.GetValue("LKKSN"),
                    Specification = x.GetValue("specification"),
                    Count = x.GetDecimal("count"),
                    MesUnitShort = x.GetValue("unit"),
                    IsValidForever = (x.GetInt("valid_forever") ?? 0) > 0,
                    ValidUntil = x.GetDate("valid_until"),
                    IsWrittenOff = x.GetValue("is_written_off") == "1"
                });

            #endregion

            return View(model);
        }

        /// <summary> Вход в инструмент добавления новой поставки </summary>
        /// <param name="id">Номер спецификации, для которой регистрируется поставка </param>
        [HttpGet]
        public IActionResult Add(int? id)
        {
            // ЛКК номер и название спецификации
            if (id == null || id < 1 || id > 999)
                return this.Error("Системная ошибка",
                    "При получении запроса на новую поставку номер спецификации был не указан, " +
                    "либо указан не верно. Обратитесь к разработчику.");

            var model = new ReactivesAddModel
            {
                Lkksn_SpecificationId = (int)id,
                SpecificationName = _connector.GetValue($"select \"name\" from \"Reactives_Specifications\" where \"Id\" = {id};", out var error)
            };

            if (string.IsNullOrWhiteSpace(model.SpecificationName))
                return this.Error("Ошибка базы данных",
                    "При попытке загрузки данных о выбранной спецификации для новой поставки произошла ошибка. " +
                    error);

            // ЛКК номер новой поставки (номер сбрасывается каждый год)
            if (!_connector.TryReadData(

WebApplication/Controllers/ReactivesMovingController.cs
using System.Data;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication.Models.ReactivesMoving;
using WebApplication.Tools.DbConnector;
using WebApplication.Tools.Project;

namespace WebApplication.Controllers
{
    /// <summary> Контроллер для статистики по движению реактивов </summary>
    [Authorize]
    public class ReactivesMovingController : Controller
    {
        /// <summary> Соединитель с базой данных </summary>
        private readonly IDbConnector _connector;

        /// <summary> Конструктор собирает сервисы </summary>
        /// <param name="connector">Сервмс вязи с базой данных</param>
        public ReactivesMovingController(IDbConnector connector)
            => _connector = connector;

        /// <summary> Первая фильтрация </summary>
        /// <param name="model">Модель фитров и результатов</param>
        public IActionResult Index(MovingIndexFilterModel model)
        {
            // перезагружает банные из базы для списков
            model ??= new MovingIndexFilterModel();

            if (!_connector.TryReadData("select \"Id\", \"name\" from \"Reactives_Specifications\";", out var data, out var error))
                return this.Error("Ошибка базы данных", 
                    "Движение реагентов, просмотр. При загрузке данных о спецификациях произошла ошибка. " + error);
            model.Specifications = data?.Rows.Cast<DataRow>()
                .Select(x => new SelectListItem(x.GetValue("name"), x.GetValue("Id"), false));

            if (!_connector.TryReadData("select \"code\", \"name\" from \"Reactives_Attributes\";", out data, out error))
                return this.Error("Ошибка базы данных", 
                    "Движение реагентов, просмотр. При загрузке данных об атрибутах произошла ошибка. " + error);
            model.Attributes = data?.Rows.Cast<DataRow>()
                .ToDictionary(x => x.GetValue("code")[0], x => x.GetValue("name"));
            model.FilterAttributesOn ??= model.Attributes?.ToDictionary(x => x.Key, x => false);
            model.FilterAttributesOff ??= model.Attributes?.ToDictionary(x => x.Key, x => false);

            if (!_connector.TryReadData("select \"Id\", \"name\" from \"Users\"", out data, out error))
                return this.Error("Ошибка базы данных", 
                    "Движение реагентов, просмотр. При загрузке данных о  произошла ошибка. " + error);
            model.Users = data?.Rows.Cast<DataRow>()
                .Select(x => new SelectListItem(x.GetValue("name"), x.GetValue("Id"), false));

            // получает данные по фильтрам от базы
            var builder = new StringBuilder
            (
                "select " +
                    "c.\"LKKSN\" as \"lkksn\", " +
                    "s.\"Id\" as \"spec_Id\", " +
                    "s.\"name\" as \"spec_name\", " +
                    "c.\"count_difference\" as \"difference\", " +
                    "m.\"short\" as \"mes_units\", " +
                    "c.\"record_comment\", " +
                    "u.\"name\" as \"user_name\", " +
                    "c.\"created_at_date\" as \"moving_datetime\" " +
                "from \"Reactives_Changes\" c " +
                    "inner join \"Reactives_Arrivals\" a on a.\"LKKSN\" = c.\"LKKSN\" " +
                    "inner join \"Reactives_Specifications\" s on a.\"LKKSN_specification_id\" = s.\"Id\" " +
                    "inner join \"Reactives_Mes_Units\" m on a.\"start_state_mes_unit_name\" = m.\"name\" " +
                    "left join \"Users\" u on u.\"Id\" = c.\"created_by\" " +
                "where c.\"count_difference\" is not null and c.\"count_difference\" <> 0 " +
                    $"and c.\"created_at_date\" between \'{model.FilterStartDate:yyyy-MM-dd}\' and \'{model.FilterEndDate:yyyy-MM-dd}\' "
            );

            if (!string.IsNullOrWhiteSpace(model.FilterInsertedSpecification))
                builder.Append($" and s.\"upper_name\" like \'%{model.FilterInsertedSpecification}%\' ");
            else if (model.FilterSelectedSpecification != null)
                builder.Append($" and s.\"Id\" = {model.FilterSelectedSpecification} ");

            if (model.FilterAttributesOn != null)
                foreach (var atrOn in model.FilterAttributesOn.Where(x => x.Value))
                    builder.Append($" and a.\"current_state_attribute_string\" like \'%{atrOn.Key}%\' ");

            if (model.FilterAttributesOff != null)
                foreach (var atrOff in model.FilterAttributesOff.Where(x => x.Value))
                    builder.Append(" and (a.\"current_state_attribute_string\" is null " +
                                   $"or a.\"current_state_attribute_string\" not like \'%{atrOff.Key}%\') ");

            if (model.FilterSelectedUser != null)
                builder.Append($" and u.\"Id\" = {model.FilterSelectedUser} ");

            builder.Append("order by c.\"created_at_date\";");

            if (!_connector.TryReadData(builder.ToString(), out data, out error))
                return this.Error("Ошибка базы данных", "Движение реактивов, просмотр. При загрузке данных по запросу произошла ошибка" + error);

            if (data == null || data.Rows.Count < 1) return View(model);

            model.Rows = data.Rows.Cast<DataRow>()
                .Select(x => new MovingIndexResultsRowModel
                {
                    Lkksn = x.GetValue("lkksn"),
                    SpecificationId = x.GetInt("spec_Id"),
                    SpecificationName =  x.GetValue("spec_name"),
                    Difference = x.GetDecimal("difference") ?? 0,
                    MesUnits = x.GetValue("mes_units"),
                    RecordComment = x.GetValue("record_comment"),
                    UserName = x.GetValue("user_name"),
                    MovingDateTime = x.GetDate("moving_datetime")
                });

            return View(model);
        }
    }
}

WebApplication/Views/ReactivesMoving/Index.cshtml
@model WebApplication.Models.ReactivesMoving.MovingIndexFilterModel
@{
    ViewData["Title"] = "Приход и расход реактивов";
    var incoming = Model.Rows?.Where(x => x.Difference >= 0).ToArray();
    var outgoing = Model.Rows?.Where(x => x.Difference < 0).ToArray();
    var arrivals = Model.Rows?.GroupBy(x => x.Lkksn).ToArray();
    var specs = Model.Rows?.GroupBy(x => x.SpecificationId).ToArray();
}

<h2>@ViewData["Title"]</h2>

<h3>
    <input type="checkbox" id="filter_chb" onclick="ShowHide('filter_chb', 'filter_div')" />
    <label for="filter_chb">Поиск</label>
</h3>

<div id="filter_div" style="display: none">
    <form asp-controller="ReactivesMoving" asp-action="Index">
        <table>
            <tr>
                <th>Отчётные даты</th>
                <td>
                    начало <input type="date" asp-for="FilterStartDate" /><br />
                    конец <input type="date" asp-for="FilterEndDate" />
                </td>
            </tr>
            <tr>
                <th>Спецификация</th>
                <td>
                    <input type="text" asp-for="FilterInsertedSpecification" />
                    <select asp-for="FilterSelectedSpecification" asp-items="@Model.Specifications">
                        <option value=""></option>
                    </select>
                </td>
            </tr>
            <tr>
                <th style="vertical-align: top">С указанными атрибутами</th>
                <td>
                    @if (Model.Attributes != null && Model.Attributes.Any())
                    {
                        @foreach (var pair in Model.FilterAttributesOn)
                        {
                            @Html.CheckBoxFor(m => m.FilterAttributesOn[pair.Key], pair.Value)
                            <label for="FilterAttributesOn_@(pair.Key)_">
                                @if (Model.Attributes.ContainsKey(pair.Key))
                                {
                                    <text>@Model.Attributes[pair.Key]</text>
                                }
                                else
                                {
                                    <text>Атрибут @pair.Value</text>
                                }
                            </label>
                        }
                    }
                    else
                    {
                        <span>Атрибуты в базе данных не зарегистрированы</span>
                    }
                </td>
            </tr>
            <tr>
                <th style="vertical-align: top">Без указанных атрибутов</th>
                <td>
                    @if (Model.Attributes != null && Model.Attributes.Any())
                    {
                        @foreach (var pair in Model.FilterAttributesOff)
                        {
                            @Html.CheckBoxFor(m => m.FilterAttributesOff[pair.Key], pair.Value)
                            <label for="FilterAttributesOff_@(pair.Key)_">
                                @if (Model.Attributes.ContainsKey(pair.Key))
                                {
                                    <text>@Model.Attributes[pair.Key]</text>
                                }
                                else
                                {
                                    <text>Атрибут @pair.Value</text>
                                }
                            </label>
                        }
                    }
                    else
                    {
                        <span>Атрибуты в базе данных не зарегистрированы</span>
                    }
                </td>
            </tr>
            <tr>
                <th>Пользователь</th>
                <td>
                    <select asp-items="@Model.Users" asp-for="FilterSelectedUser">
                        <option value=""></option>
                    </select>
                </td>
            </tr>
        </table>
        <div style="text-align: center">
            <a asp-controller="ReactivesMoving" asp-action="Index" style="text-decoration: none">
                <input type="button" class="btn btn-outline-dark margined-for-5px" value="Сброс" />
            </a>
            <input type="submit" class="btn btn-outline-dark margined-for-5px" value="Поиск" />
        </div>
    </form>
</div>

<h3>Результаты поиска</h3>

<div>
    <h4>Приход</h4>
    @if (incoming == null || !incoming.Any())
    {
        <span>Фактов прихода реактивов по выбранным Вами фильтрам не обнаружено</span>
    }
    else
    {
        <table class="table-bordered hightlightrows" style="width: 100%">
            <tr>
                <th style="text-align: center">Дата</th>
                <th style="text-align: center">Спецификация</th>
                <th style="text-align: center">Поставка</th>
                <th style="text-align: center">Объём</th>
                <th style="text-align: center">Комментарий</th>
                <th style="text-align: center">Пользователь</th>
            </tr>
            @foreach (var row in incoming)
            {
                <tr>
                    <td>@row.MovingDateTime?.ToString("dd.MM.yyyy HH:mm:ss")</td>
                    <td>
                        <a asp-controller="Specifications" asp-action="Info" asp-route-id="@row.SpecificationId">
                            @row.SpecificationId?.ToString("D3") - @row.SpecificationName
                        </a>
                    </td>
                    <td>
                        <a asp-controller="Reactives" asp-action="Info" asp-route-lkksn="@row.Lkksn">
                            @row.Lkksn
                        </a>
                    </td>
                    <td style="color: darkgreen">+@row.Difference @row.MesUnits</td>
                    <td style="font-size: small">@row.RecordComment</td>
                    <td>@row.UserName</td>
                </tr>
            }
        </table>
    }
</div>

<div>
    <h4>Расход</h4>
    @if (outgoing == null || !outgoing.Any())
    {
        <span>Фактов прихода реактивов по выбранным Вами фильтрам не обнаружено</span>
    }
    else
    {
        <table class="table-bordered hightlightrows" style="width: 100%">
            <tr>
                <th style="text-align: center">Дата</th>
                <th style="text-align: center">Спецификация</th>
                <th style="text-align: center">Поставка</th>
                <th style="text-align: center">Объём</th>
                <th style="text-align: center">Комментарий</th>
                <th style="text-align: center">Пользователь</th>
            </tr>
            @foreach (var row in outgoing)
            {
                <tr>
                    <td>@row.MovingDateTime?.ToString("dd.MM.yyyy HH:mm:ss")</td>
                    <td>
                        <a asp-controller="Specifications" asp-action="Info" asp-route-id="@row.SpecificationId">
                            @row.SpecificationId?.ToString("D3") - @row.SpecificationName
                        </a>
                    </td>
                    <td>
                        <a asp-controller="Reactives" asp-action="Info" asp-route-lkksn="@row.Lkksn">
                            @row.Lkksn
                        </a>
                    </td>
                    <td style="color: darkred">@row.Difference @row.MesUnits</td>
                    <td style="font-size: small">@row.RecordComment</td>
                    <td>@row.UserName</td>
                </tr>
            }
        </table>
    }
</div>

@if (arrivals != null && arrivals.Any())
{
    <div>
        <h4>По поставкам</h4>

        <table class="table-bordered hightlightrows" style="width: 100%">
            <tr>
                <th style="text-align: center">Дата</th>
                <th style="text-align: center">Спецификация</th>
                <th style="text-align: center">Приход</th>
                <th style="text-align: center">Расход</th>
                <th style="text-align: center">Ед.</th>
                <th style="text-align: center">Комментарий</th>
                <th style="text-align: center">Пользователь</th>
            </tr>
            @foreach (var arrival in arrivals)
            {
                <tr>

                    <th colspan="7" style="text-align: center">
                        <a asp-controller="Reactives" asp-action="Info" asp-route-lkksn="@arrival.Key">
                            @arrival.Key
                        </a>
                    </th>
                </tr>
                @foreach (var row in arrival)
                {

                    <tr>
                        <td>@row.MovingDateTime?.ToString("dd.MM.yyyy HH:mm:ss")</td>
                        <td>
                            <a asp-controller="Specifications" asp-action="Info" asp-route-id="@row.SpecificationId">
                                @row.SpecificationId?.ToString("D3") - @row.SpecificationName
                            </a>
                        </td>
                        <td style="color: darkgreen">
                            @if (row.Difference >= 0)
                            {
                                <text>+@row.Difference</text>
                            }
                        </td>
                        <td style="color: darkred">
                            @if (row.Difference < 0)
                            {
                                <text>@row.Difference</text>
                            }
                        </td>
                        <td>@row.MesUnits</td>
                        <td style="font-size: small">@row.RecordComment</td>
                        <td>@row.UserName</td>
                    </tr>
                }
            }
        </table>
    </div>
}

@if (specs != null && specs.Any())
{
    <div>
        <h4>По спецификациям</h4>

        <table class="table-bordered hightlightrows" style="width: 100%">
            <tr>
                <th style="text-align: center">Дата</th>
                <th style="text-align: center">Поставка</th>
                <th style="text-align: center">Приход</th>
                <th style="text-align: center">Расход</th>
                <th style="text-align: center">Ед.</th>
                <th style="text-align: center">Комментарий</th>
                <th style="text-align: center">Пользователь</th>
            </tr>
            @foreach (var spec in specs)
            {
                <tr>

                    <th colspan="7" style="text-align: center">
                        <a asp-controller="Specifications" asp-action="Info" asp-route-id="@spec.Key">
                            @spec.Key?.ToString("D3") - @Model.Rows.Where(x => x.SpecificationId == spec.Key).Select(x => x.SpecificationName).FirstOrDefault()
                        </a>
                    </th>
                </tr>
                @foreach (var row in spec)
                {

                    <tr>
                        <td>@row.MovingDateTime?.ToString("dd.MM.yyyy HH:mm:ss")</td>
                        <td>
                            <a asp-controller="Reactives" asp-action="Info" asp-route-lkksn="@row.Lkksn">
                                @row.Lkksn
                            </a>
                        </td>
                        <td style="color: darkgreen">
                            @if (row.Difference >= 0)
                            {
                                <text>+@row.Difference</text>
                            }
                        </td>
                        <td style="color: darkred">
                            @if (row.Difference < 0)
                            {
                                <text>@row.Difference</text>
                            }
                        </td>
                        <td>@row.MesUnits</td>
                        <td style="font-size: small">@row.RecordComment</td>
                        <td>@row.UserName</td>
                    </tr>
                }
            }
        </table>
    </div>
}